pipeline {
    agent { label 't813 && robot' }

    parameters {
        string(name: 'REPOSITORY_URL', defaultValue: 'https://github.com/stella555359/jenkins_robotframework.git', description: 'jenkins_robotframework repository URL that contains Job DSL files.')
        string(name: 'REPOSITORY_REF', defaultValue: 'main', description: 'Branch, tag, or commit used by the seed job.')
        string(name: 'REPOSITORY_CREDENTIALS_ID', defaultValue: '', description: 'Optional Jenkins credentials id for checking out this repository.')
        string(name: 'JOB_DSL_TARGETS', defaultValue: 'jenkins-integration/jobs/*_job.groovy', description: 'Job DSL scripts to execute. Use underscore filenames because current Job DSL rejects hyphenated script names.')
        booleanParam(name: 'IGNORE_REMOVED_JOBS', defaultValue: true, description: 'Keep Jenkins jobs that are no longer generated by the current DSL files.')
    }

    stages {
        stage('Checkout Seed Source') {
            steps {
                script {
                    def checkoutArgs = [
                        url: params.REPOSITORY_URL,
                        branch: params.REPOSITORY_REF,
                    ]
                    if (params.REPOSITORY_CREDENTIALS_ID?.trim()) {
                        checkoutArgs.credentialsId = params.REPOSITORY_CREDENTIALS_ID.trim()
                    }
                    git checkoutArgs
                }
            }
        }

        stage('Run Job DSL') {
            steps {
                script {
                    jobDsl(
                        targets: params.JOB_DSL_TARGETS,
                        lookupStrategy: 'JENKINS_ROOT',
                        removedJobAction: params.IGNORE_REMOVED_JOBS ? 'IGNORE' : 'DISABLE',
                        removedViewAction: 'IGNORE',
                        // This controlled seed job is run by an administrator to apply reviewed Job DSL from this repository.
                        sandbox: false,
                    )
                }
            }
        }
    }

    post {
        always {
            archiveArtifacts artifacts: 'jenkins-integration/jobs/*_job.groovy', allowEmptyArchive: true
        }
    }
}
